# Generated by Django 3.1.5 on 2021-01-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210125_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationevents',
            old_name='sent',
            new_name='wasSent',
        ),
    ]
