# Generated by Django 3.1.5 on 2021-01-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210125_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpense',
            name='duration',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='variableexpense',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
