# Generated by Django 3.1.5 on 2021-01-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210125_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevents',
            name='email',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevents',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevents',
            name='wasSent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
