# Generated by Django 3.1.5 on 2021-01-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_fixedexpense_begining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpense',
            name='begining',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
