# Generated by Django 3.1.5 on 2021-01-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210128_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphonenumber',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
