# Generated by Django 3.1.5 on 2021-01-30 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210129_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpense',
            name='begining',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 13, 55, 26)),
        ),
        migrations.AlterField(
            model_name='variableexpense',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 13, 55, 26)),
        ),
    ]
